name: "Build and deploy to nuget.org"

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: Fedodo/Fedodo.Pipelines/BuildAndDeployNuGet@main
        with:
          PROJECT_PATH: "Fedodo.NuGet.ActivityPub.Model/Fedodo.NuGet.ActivityPub.Model.csproj"
          PROJECT_TEST_PATH: "Fedodo.NuGet.ActivityPub.Model/Fedodo.NuGet.ActivityPub.Model.Test.csproj"
          NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"
          VERSION: 2.0.${{ github.run_number }}
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
          PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
